import Head from 'next/head'
import Form from '../components/form'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mail Gönderme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
      
    </div>
  )
}
